def kuwo_base64_decrypt(value: str) -> str: ...

def extract_qmc_raw_key_from_ekey(ekey: str) -> bytes: ...

def derive_qmc_key(raw_key: bytes) -> bytes: ...

def decrypt_qmc_bytes(data: bytes, raw_key: bytes, offset: int = 0) -> bytes: ...

def decrypt_mflac_file(
    source_path: str,
    target_path: str,
    ekey: str,
    chunk_size: int = 65536,
) -> None: ...
